# AKS Deployment Pipeline — Build, Push, Deploy
# Builds Docker images for API and Dashboard, pushes to ACR, deploys to AKS.
# Flow: Build Images → Push to ACR → Deploy DEV → Smoke Test → STAGING → PROD

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - serving/**
      - k8s/**

pr:
  branches:
    include:
      - main
  paths:
    include:
      - serving/**
      - k8s/**

pool:
  name: Default

variables:
  - name: apiImageName
    value: "churn-api"
  - name: dashboardImageName
    value: "churn-dashboard"
  - name: imageTag
    value: "$(Build.BuildId)"

stages:
  - stage: BuildAndPush
    displayName: "Build & Push Docker Images"
    variables:
      - group: aks-dev
    jobs:
      - job: BuildImages
        steps:
          - script: |
              echo "Logging in to ACR: $(ACR_LOGIN_SERVER)..."
              az acr login --name $(ACR_NAME)
            displayName: "Login to Azure Container Registry"

          - script: |
              echo "Building API image..."
              docker build \
                -t $(ACR_LOGIN_SERVER)/$(apiImageName):$(imageTag) \
                -t $(ACR_LOGIN_SERVER)/$(apiImageName):latest \
                -f serving/api/Dockerfile \
                serving/api
            displayName: "Build Churn API Image"

          - script: |
              echo "Pushing API image..."
              docker push $(ACR_LOGIN_SERVER)/$(apiImageName):$(imageTag)
              docker push $(ACR_LOGIN_SERVER)/$(apiImageName):latest
            displayName: "Push Churn API Image"

          - script: |
              echo "Building Dashboard image..."
              docker build \
                -t $(ACR_LOGIN_SERVER)/$(dashboardImageName):$(imageTag) \
                -t $(ACR_LOGIN_SERVER)/$(dashboardImageName):latest \
                -f serving/dashboard/Dockerfile \
                serving/dashboard
            displayName: "Build Dashboard Image"

          - script: |
              echo "Pushing Dashboard image..."
              docker push $(ACR_LOGIN_SERVER)/$(dashboardImageName):$(imageTag)
              docker push $(ACR_LOGIN_SERVER)/$(dashboardImageName):latest
            displayName: "Push Dashboard Image"

  - stage: DeployDev
    displayName: "Deploy to AKS — DEV"
    dependsOn: BuildAndPush
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    variables:
      - group: aks-dev
    jobs:
      - deployment: DeployToDevAKS
        environment: "telco-churn-aks-dev"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - script: |
                    az aks get-credentials --resource-group $(AKS_RESOURCE_GROUP) \
                      --name $(AKS_CLUSTER_NAME) --overwrite-existing
                  displayName: "Get AKS credentials"

                - script: |
                    kubectl apply -f k8s/namespace.yaml
                  displayName: "Create namespace"

                - script: |
                    cd k8s/overlays/dev
                    if command -v kustomize &>/dev/null; then
                      kustomize edit set image \
                        churn-api=$(ACR_LOGIN_SERVER)/$(apiImageName):$(imageTag) \
                        churn-dashboard=$(ACR_LOGIN_SERVER)/$(dashboardImageName):$(imageTag)
                      kustomize build . | kubectl apply -f -
                    else
                      kubectl kustomize . | kubectl apply -f -
                    fi
                  displayName: "Deploy DEV manifests (Kustomize)"

                - script: |
                    echo "Waiting for API rollout..."
                    kubectl rollout status deployment/dev-churn-api -n telco-churn --timeout=300s
                    echo "Waiting for Dashboard rollout..."
                    kubectl rollout status deployment/dev-churn-dashboard -n telco-churn --timeout=300s
                    echo "Deployment complete:"
                    kubectl get pods -n telco-churn -o wide
                  displayName: "Verify deployment rollout"

  - stage: SmokeTestDev
    displayName: "Smoke Test — DEV"
    dependsOn: DeployDev
    variables:
      - group: aks-dev
    jobs:
      - job: RunSmokeTests
        steps:
          - script: |
              echo "Running smoke tests against DEV API..."

              HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "$(DEV_API_URL)/health")
              if [ "$HTTP_CODE" != "200" ]; then
                echo "Health check failed: HTTP $HTTP_CODE"
                exit 1
              fi
              echo "Health check passed"

              HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "$(DEV_API_URL)/ready")
              if [ "$HTTP_CODE" != "200" ]; then
                echo "Readiness check failed: HTTP $HTTP_CODE"
                exit 1
              fi
              echo "Readiness check passed"

              curl -s "$(DEV_API_URL)/model/info" | python3 -m json.tool
              echo "Model info check passed"

              RESPONSE=$(curl -s -X POST "$(DEV_API_URL)/predict" \
                -H "Content-Type: application/json" \
                -d '{
                  "customer_id": "SMOKE-TEST-001",
                  "contract_status_ord": 3,
                  "ooc_days": 30,
                  "tenure_days": 365,
                  "calls_30d": 2,
                  "calls_90d": 5,
                  "loyalty_calls_90d": 1,
                  "speed": 80,
                  "line_speed": 65,
                  "monthly_total_mb": 50000,
                  "technology": "FTTP",
                  "sales_channel": "Online",
                  "tenure_bucket": "90d-1y"
                }')
              echo "Prediction response: $RESPONSE"

              echo "$RESPONSE" | python3 -c "
              import json, sys
              data = json.load(sys.stdin)
              assert 'risk_tier' in data, 'Missing risk_tier'
              assert 'predictions' in data, 'Missing predictions'
              assert len(data['predictions']) == 3, 'Expected 3 horizon predictions'
              print('All smoke tests PASSED')
              "
            displayName: "Run API smoke tests"

  - stage: DeployStaging
    displayName: "Deploy to AKS — STAGING"
    dependsOn: SmokeTestDev
    variables:
      - group: aks-staging
    jobs:
      - deployment: DeployToStagingAKS
        environment: "telco-churn-aks-staging"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - script: |
                    az aks get-credentials --resource-group $(AKS_RESOURCE_GROUP) \
                      --name $(AKS_CLUSTER_NAME) --overwrite-existing
                  displayName: "Get AKS credentials"

                - script: |
                    cd k8s/overlays/staging
                    kubectl kustomize . | kubectl apply -f -
                  displayName: "Deploy STAGING manifests (Kustomize)"

                - script: |
                    kubectl rollout status deployment/staging-churn-api -n telco-churn --timeout=300s
                    kubectl rollout status deployment/staging-churn-dashboard -n telco-churn --timeout=300s
                    kubectl get pods -n telco-churn -o wide
                    kubectl get hpa -n telco-churn
                  displayName: "Verify STAGING deployment + HPA"

  - stage: DeployProd
    displayName: "Deploy to AKS — PRODUCTION"
    dependsOn: DeployStaging
    variables:
      - group: aks-prod
    jobs:
      - deployment: DeployToProdAKS
        environment: "telco-churn-aks-prod"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - script: |
                    az aks get-credentials --resource-group $(AKS_RESOURCE_GROUP) \
                      --name $(AKS_CLUSTER_NAME) --overwrite-existing
                  displayName: "Get AKS credentials"

                - script: |
                    cd k8s/overlays/prod
                    kubectl kustomize . | kubectl apply -f -
                  displayName: "Deploy PROD manifests (Kustomize)"

                - script: |
                    echo "Verifying PRODUCTION deployment..."
                    kubectl rollout status deployment/prod-churn-api -n telco-churn --timeout=600s
                    kubectl rollout status deployment/prod-churn-dashboard -n telco-churn --timeout=600s
                    echo ""
                    echo "=== Pod Status ==="
                    kubectl get pods -n telco-churn -o wide
                    echo ""
                    echo "=== HPA Status ==="
                    kubectl get hpa -n telco-churn
                    echo ""
                    echo "=== Services ==="
                    kubectl get svc -n telco-churn
                    echo ""
                    echo "=== Ingress ==="
                    kubectl get ingress -n telco-churn
                  displayName: "Verify PROD deployment + auto-scaling"
