# Infrastructure Pipeline — Terraform Plan & Apply
# Provisions all Azure resources per environment.
# Flow: terraform plan (on PR) → terraform apply (on merge to main)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - infrastructure/**

pr:
  branches:
    include:
      - main
  paths:
    include:
      - infrastructure/**

pool:
  name: Default

variables:
  - name: terraformVersion
    value: "1.7.0"
  - name: workingDirectory
    value: "$(System.DefaultWorkingDirectory)/infrastructure"
  - name: TF_PLUGIN_CACHE_DIR
    value: "/Users/kanaanudo/.terraform.d/plugin-cache"

stages:
  - stage: Validate
    displayName: "Terraform Validate"
    jobs:
      - job: ValidateTerraform
        steps:
          - script: |
              mkdir -p $(TF_PLUGIN_CACHE_DIR)
              if ! terraform version 2>/dev/null; then
                echo "Installing Terraform $(terraformVersion)..."
                brew tap hashicorp/tap
                brew install hashicorp/tap/terraform
              fi
              terraform version
            displayName: "Ensure Terraform installed"

          - script: |
              cd $(workingDirectory)
              terraform init -backend=false
              terraform validate
            displayName: "terraform validate"

          - script: |
              cd $(workingDirectory)
              terraform fmt -check -recursive
            displayName: "terraform fmt check"

  - stage: DeployDev
    displayName: "Deploy Infra — DEV"
    dependsOn: Validate
    variables:
      - group: azure-infra-dev
    jobs:
      - deployment: TerraformApplyDev
        environment: "telco-churn-infra-dev"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - script: |
                    export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
                    export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
                    export ARM_TENANT_ID=$(ARM_TENANT_ID)
                    export ARM_SUBSCRIPTION_ID=$(AZURE_SUBSCRIPTION_ID)
                    cd $(workingDirectory)
                    terraform init \
                      -backend-config=environments/dev/backend.tfvars \
                      -backend-config="access_key=$(TF_STATE_ACCESS_KEY)"
                  displayName: "terraform init (DEV)"

                - script: |
                    export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
                    export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
                    export ARM_TENANT_ID=$(ARM_TENANT_ID)
                    export ARM_SUBSCRIPTION_ID=$(AZURE_SUBSCRIPTION_ID)
                    cd $(workingDirectory)
                    terraform plan \
                      -var-file=environments/dev/terraform.tfvars \
                      -var="subscription_id=$(AZURE_SUBSCRIPTION_ID)" \
                      -out=dev.tfplan
                  displayName: "terraform plan (DEV)"

                - script: |
                    export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
                    export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
                    export ARM_TENANT_ID=$(ARM_TENANT_ID)
                    export ARM_SUBSCRIPTION_ID=$(AZURE_SUBSCRIPTION_ID)
                    cd $(workingDirectory)
                    terraform apply -auto-approve dev.tfplan
                  displayName: "terraform apply (DEV)"
                  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')

  - stage: DeployStaging
    displayName: "Deploy Infra — STAGING"
    dependsOn: DeployDev
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    variables:
      - group: azure-infra-staging
    jobs:
      - deployment: TerraformApplyStaging
        environment: "telco-churn-infra-staging"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - script: |
                    export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
                    export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
                    export ARM_TENANT_ID=$(ARM_TENANT_ID)
                    export ARM_SUBSCRIPTION_ID=$(AZURE_SUBSCRIPTION_ID)
                    cd $(workingDirectory)
                    terraform init \
                      -backend-config=environments/staging/backend.tfvars \
                      -backend-config="access_key=$(TF_STATE_ACCESS_KEY)"
                  displayName: "terraform init (STAGING)"

                - script: |
                    export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
                    export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
                    export ARM_TENANT_ID=$(ARM_TENANT_ID)
                    export ARM_SUBSCRIPTION_ID=$(AZURE_SUBSCRIPTION_ID)
                    cd $(workingDirectory)
                    terraform plan \
                      -var-file=environments/staging/terraform.tfvars \
                      -var="subscription_id=$(AZURE_SUBSCRIPTION_ID)" \
                      -out=staging.tfplan
                  displayName: "terraform plan (STAGING)"

                - script: |
                    export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
                    export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
                    export ARM_TENANT_ID=$(ARM_TENANT_ID)
                    export ARM_SUBSCRIPTION_ID=$(AZURE_SUBSCRIPTION_ID)
                    cd $(workingDirectory)
                    terraform apply -auto-approve staging.tfplan
                  displayName: "terraform apply (STAGING)"

  - stage: DeployProd
    displayName: "Deploy Infra — PRODUCTION"
    dependsOn: DeployStaging
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    variables:
      - group: azure-infra-prod
    jobs:
      - deployment: TerraformApplyProd
        environment: "telco-churn-infra-prod"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - script: |
                    export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
                    export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
                    export ARM_TENANT_ID=$(ARM_TENANT_ID)
                    export ARM_SUBSCRIPTION_ID=$(AZURE_SUBSCRIPTION_ID)
                    cd $(workingDirectory)
                    terraform init \
                      -backend-config=environments/prod/backend.tfvars \
                      -backend-config="access_key=$(TF_STATE_ACCESS_KEY)"
                  displayName: "terraform init (PROD)"

                - script: |
                    export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
                    export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
                    export ARM_TENANT_ID=$(ARM_TENANT_ID)
                    export ARM_SUBSCRIPTION_ID=$(AZURE_SUBSCRIPTION_ID)
                    cd $(workingDirectory)
                    terraform plan \
                      -var-file=environments/prod/terraform.tfvars \
                      -var="subscription_id=$(AZURE_SUBSCRIPTION_ID)" \
                      -out=prod.tfplan
                  displayName: "terraform plan (PROD)"

                - script: |
                    export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
                    export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
                    export ARM_TENANT_ID=$(ARM_TENANT_ID)
                    export ARM_SUBSCRIPTION_ID=$(AZURE_SUBSCRIPTION_ID)
                    cd $(workingDirectory)
                    terraform apply -auto-approve prod.tfplan
                  displayName: "terraform apply (PROD)"
